#!/usr/bin/env python3
"""Generate a Markdown reference document from Playwright E2E spec files.

Parses all ``.spec.ts`` files under ``e2e/specs/`` and writes a summary
to ``e2e/docs/reference/specs.md``.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SPECS_DIR = REPO_ROOT / "e2e" / "specs"
OUTPUT = REPO_ROOT / "e2e" / "docs" / "reference" / "specs.md"

DESCRIBE_RE = re.compile(r"test\.describe(?:\.\w+)?\(['\"]([^'\"]+)['\"]")
TEST_RE = re.compile(r"\btest(?:\.(?!describe)\w+)?\(['\"]([^'\"]+)['\"]")


def parse_spec(file: Path) -> list[tuple[str, list[str]]]:
    """Return list of ``(describe_label, [test_labels])`` for a spec file."""
    text = file.read_text(encoding="utf-8")
    suites: list[tuple[str, list[str]]] = []

    describe_matches = list(DESCRIBE_RE.finditer(text))

    if not describe_matches:
        orphan_tests = [m.group(1) for m in TEST_RE.finditer(text)]
        if orphan_tests:
            suites.append(("(unnamed)", orphan_tests))
        return suites

    for i, dm in enumerate(describe_matches):
        section_start = dm.start()
        section_end = (
            describe_matches[i + 1].start()
            if i + 1 < len(describe_matches)
            else len(text)
        )
        section = text[section_start:section_end]

        describe_label = dm.group(1)
        tests = [m.group(1) for m in TEST_RE.finditer(section)]
        suites.append((describe_label, tests))

    return suites


def generate() -> int:
    """Main entry point. Returns exit code."""
    spec_files = sorted(SPECS_DIR.rglob("*.spec.ts"))

    if not spec_files:
        print("No spec files found.", file=sys.stderr)
        return 1

    all_entries: list[tuple[Path, list[tuple[str, list[str]]]]] = []
    total_tests = 0

    for f in spec_files:
        suites = parse_spec(f)
        count = sum(len(tests) for _, tests in suites)
        total_tests += count
        rel = f.relative_to(REPO_ROOT)
        print(f"[specs] {rel} \u2014 {count} tests", file=sys.stderr)
        all_entries.append((f, suites))

    lines: list[str] = [
        "# E2E Spec Reference",
        "",
        "> Auto-generated by scripts/gen_e2e_spec_docs.py. Do not edit manually.",
        "",
        f"**Total**: {len(spec_files)} spec files, {total_tests} tests",
        "",
        "---",
        "",
    ]

    for f, suites in all_entries:
        rel = f.relative_to(REPO_ROOT)
        parts = rel.parts  # e.g. ('e2e','specs','arduino_dash','dashboard.spec.ts')
        group = parts[-2]  # arduino_dash or medminder_dash
        fname = parts[-1]  # dashboard.spec.ts
        count = sum(len(tests) for _, tests in suites)

        lines.append(f"## {group} / [{fname}](../../specs/{group}/{fname})")
        lines.append("")
        lines.append(f"*{count} tests*")
        lines.append("")

        for describe_label, test_labels in suites:
            lines.append(f"### {describe_label}")
            for t in test_labels:
                lines.append(f"- **{t}**")
            lines.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")

    print(f"\n[specs] Wrote {OUTPUT}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(generate())
