# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cc/arduino/cli/commands/v1/monitor.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'cc/arduino/cli/commands/v1/monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cc.arduino.cli.commands.v1 import common_pb2 as cc_dot_arduino_dot_cli_dot_commands_dot_v1_dot_common__pb2
from cc.arduino.cli.commands.v1 import port_pb2 as cc_dot_arduino_dot_cli_dot_commands_dot_v1_dot_port__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(cc/arduino/cli/commands/v1/monitor.proto\x12\x1a\x63\x63.arduino.cli.commands.v1\x1a\'cc/arduino/cli/commands/v1/common.proto\x1a%cc/arduino/cli/commands/v1/port.proto\"\xe2\x01\n\x0eMonitorRequest\x12J\n\x0copen_request\x18\x01 \x01(\x0b\x32\x32.cc.arduino.cli.commands.v1.MonitorPortOpenRequestH\x00\x12\x11\n\x07tx_data\x18\x02 \x01(\x0cH\x00\x12U\n\x15updated_configuration\x18\x03 \x01(\x0b\x32\x34.cc.arduino.cli.commands.v1.MonitorPortConfigurationH\x00\x12\x0f\n\x05\x63lose\x18\x04 \x01(\x08H\x00\x42\t\n\x07message\"\xe0\x01\n\x16MonitorPortOpenRequest\x12\x36\n\x08instance\x18\x01 \x01(\x0b\x32$.cc.arduino.cli.commands.v1.Instance\x12.\n\x04port\x18\x02 \x01(\x0b\x32 .cc.arduino.cli.commands.v1.Port\x12\x0c\n\x04\x66qbn\x18\x03 \x01(\t\x12P\n\x12port_configuration\x18\x04 \x01(\x0b\x32\x34.cc.arduino.cli.commands.v1.MonitorPortConfiguration\"\xa5\x01\n\x0fMonitorResponse\x12\x0f\n\x05\x65rror\x18\x01 \x01(\tH\x00\x12\x11\n\x07rx_data\x18\x02 \x01(\x0cH\x00\x12P\n\x10\x61pplied_settings\x18\x03 \x01(\x0b\x32\x34.cc.arduino.cli.commands.v1.MonitorPortConfigurationH\x00\x12\x11\n\x07success\x18\x04 \x01(\x08H\x00\x42\t\n\x07message\"\x82\x01\n#EnumerateMonitorPortSettingsRequest\x12\x36\n\x08instance\x18\x01 \x01(\x0b\x32$.cc.arduino.cli.commands.v1.Instance\x12\x15\n\rport_protocol\x18\x02 \x01(\t\x12\x0c\n\x04\x66qbn\x18\x03 \x01(\t\"r\n$EnumerateMonitorPortSettingsResponse\x12J\n\x08settings\x18\x01 \x03(\x0b\x32\x38.cc.arduino.cli.commands.v1.MonitorPortSettingDescriptor\"s\n\x1cMonitorPortSettingDescriptor\x12\x12\n\nsetting_id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x13\n\x0b\x65num_values\x18\x04 \x03(\t\x12\r\n\x05value\x18\x05 \x01(\tBHZFgithub.com/arduino/arduino-cli/rpc/cc/arduino/cli/commands/v1;commandsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cc.arduino.cli.commands.v1.monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/arduino/arduino-cli/rpc/cc/arduino/cli/commands/v1;commands'
  _globals['_MONITORREQUEST']._serialized_start=153
  _globals['_MONITORREQUEST']._serialized_end=379
  _globals['_MONITORPORTOPENREQUEST']._serialized_start=382
  _globals['_MONITORPORTOPENREQUEST']._serialized_end=606
  _globals['_MONITORRESPONSE']._serialized_start=609
  _globals['_MONITORRESPONSE']._serialized_end=774
  _globals['_ENUMERATEMONITORPORTSETTINGSREQUEST']._serialized_start=777
  _globals['_ENUMERATEMONITORPORTSETTINGSREQUEST']._serialized_end=907
  _globals['_ENUMERATEMONITORPORTSETTINGSRESPONSE']._serialized_start=909
  _globals['_ENUMERATEMONITORPORTSETTINGSRESPONSE']._serialized_end=1023
  _globals['_MONITORPORTSETTINGDESCRIPTOR']._serialized_start=1025
  _globals['_MONITORPORTSETTINGDESCRIPTOR']._serialized_end=1140
# @@protoc_insertion_point(module_scope)
