# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cc/arduino/cli/commands/v1/port.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'cc/arduino/cli/commands/v1/port.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%cc/arduino/cli/commands/v1/port.proto\x12\x1a\x63\x63.arduino.cli.commands.v1\"\xde\x01\n\x04Port\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x10\n\x08protocol\x18\x03 \x01(\t\x12\x16\n\x0eprotocol_label\x18\x04 \x01(\t\x12\x44\n\nproperties\x18\x05 \x03(\x0b\x32\x30.cc.arduino.cli.commands.v1.Port.PropertiesEntry\x12\x13\n\x0bhardware_id\x18\x06 \x01(\t\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42HZFgithub.com/arduino/arduino-cli/rpc/cc/arduino/cli/commands/v1;commandsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cc.arduino.cli.commands.v1.port_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZFgithub.com/arduino/arduino-cli/rpc/cc/arduino/cli/commands/v1;commands'
  _globals['_PORT_PROPERTIESENTRY']._loaded_options = None
  _globals['_PORT_PROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_PORT']._serialized_start=70
  _globals['_PORT']._serialized_end=292
  _globals['_PORT_PROPERTIESENTRY']._serialized_start=243
  _globals['_PORT_PROPERTIESENTRY']._serialized_end=292
# @@protoc_insertion_point(module_scope)
